// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcLandlord.Data;

#nullable disable

namespace Restify.Migrations
{
    [DbContext(typeof(MvcLandlordContext))]
    [Migration("20240504124839_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restify.Models.Landlord", b =>
                {
                    b.Property<int>("landlord_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("landlord_id"));

                    b.Property<string>("landlord_contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("landlord_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("landlord_firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("landlord_lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("landlord_password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("landlord_id");

                    b.ToTable("Landlord");
                });
#pragma warning restore 612, 618
        }
    }
}
